### ISSUE TITLE
File Uploader Bug

### ISSUE THREAD

**Issue by Zero0Zed** [alishahidi/apantos#1]
bug in file system/Request/Traits/HasRunValidation.php
replace checkFileExist method with this

```php
protected function checkFileExist($name)
    {
        return !empty($this->files[$name]["name"]) || !empty($this->request[$name]["name"]);
    }
```
File uploader bug , we can send any thing to file uploader instead image file

**Comment by alishahidi** [comment]
thanks a lot
i fixed this problem
on this commit (https://github.com/Alishahidi/apantos/commit/867817195076d502055d2967b90dbf5692db9a2e)
#1
